progress-indicatorのborderのサイズ展開をする
pepabo/inhouse-tokens pull request #11
Opened 2024-10-01 08:16 UTC by chocolatina

progress-indicatorのborderの太さを選択できるようにしたいため、border.yamlのprogress-indicatorにs,m,lを追加します

2024-10-01 08:42 UTC, piyoppi requested changes

2024-10-01 08:42 UTC, piyoppi commented on tokens/pepper/size/border.yaml
> +          subitem: l
Flavorを入れ替えたときに同一の挙動を得るためには、tokensのフォーマットはすべてのFlavorで同一であることが望ましいです。この差分が各tokensに対して全てに適用されている必要があるので、https://github.com/pepabo/inhouse-tokens/tree/main/tokens 配下の全てのトークンに同様の差分が必要です。

2024-10-01 08:42 UTC, piyoppi commented on tokens/pepper/size/border.yaml
> +          subitem: l
線分の太さの種別が妥当かどうか(たとえばデフォルト値っぽくなりそうな `m` が  `size.border.base.l.value` でよいかどうか、元々は `size.border.base.xl.value` がデフォルト値だがその兼ね合い的にも妥当か、という観点ではどうなのだろう、という気になりがあるのですが、このあたりを他の方々にも見ていただきたいです。

2024-10-01 09:12 UTC, chocolatina commented on tokens/pepper/size/border.yaml
> +          subitem: l
各tokensに対して全てに適用するよう修正しました。
https://github.com/pepabo/inhouse-tokens/pull/11/commits/45d20cb09af8c7a5609d9a66a77bee030649463f

2024-10-02 00:33 UTC, itoh4126 approved these changes
良いですね、ありがとうございます！

2024-10-02 03:05 UTC, piyoppi approved these changes

2024-10-02 03:05 UTC, piyoppi commented on tokens/pepper/size/border.yaml
> +          subitem: l
`size.border.base` はアウトラインに利用されるケースが多いものの、CircularProgressIndicatorに設定するそれはStroke的なものなので、参照すべきPrimitive Tokenが異なるということがあるのかもしれません。今後そういうものを用意するのか、などを議論できるとよさそうです。

とはいえ、現状はそういうものはなく、またFlavorでカスタマイズできるところでもあるのでこれで進めてよさそうです。

2024-10-02 04:04 UTC, piyoppi commented
対応する `@pepabo-inhouse/components-web` が v2.0.0以降なので、あわせてこの差分が入るバージョンも 2.0.0 とします

2024-10-02 04:04 UTC, merged